In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
filename = 'pima-indians-diabetes.csv'
names=['preg','plas','pres','skin', 'test', 'mass','pedi','age','class']

data=pd.read_csv(filename,names=names)
print(data.describe())

             preg        plas        pres        skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%   

In [14]:

array = data.values
# print(array[:2])

X = array[:,:8]
Y = array[:,8]

print(X[0],Y[0])

[   6.     148.      72.      35.       0.      33.6      0.627   50.   ] 1.0


In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
rX = scaler.fit_transform(X)

np.set_printoptions(precision=3)
print(X[0:3])
print(rX[0:3])

[[   6.     148.      72.      35.       0.      33.6      0.627   50.   ]
 [   1.      85.      66.      29.       0.      26.6      0.351   31.   ]
 [   8.     183.      64.       0.       0.      23.3      0.672   32.   ]]
[[ 0.353  0.744  0.59   0.354  0.     0.501  0.234  0.483]
 [ 0.059  0.427  0.541  0.293  0.     0.396  0.117  0.167]
 [ 0.471  0.92   0.525  0.     0.     0.347  0.254  0.183]]


In [18]:
from sklearn.preprocessing import StandardScaler

stdScaler = StandardScaler().fit(X)
stdreX = stdScaler.transform(X)
print(stdreX[0:3])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]]


In [23]:
#binarization
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold=0.).fit(X)
binaryX = binarizer.transform(X)

print(binaryX[0:3])

[[ 1.  1.  1.  1.  0.  1.  1.  1.]
 [ 1.  1.  1.  1.  0.  1.  1.  1.]
 [ 1.  1.  1.  0.  0.  1.  1.  1.]]
